#!/bin/bash
#PBS -k o
#PBS -M USEREMAIL
#PBS -m abe
#PHS -N bird_deblur
#PBS -j oe
#PBS -d USERDIRECTORY
#PBS -l walltime=05:00:00,nodes=1:ppn=36,feature=xeon

module load EasyBuild
module load QIIME2
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

qiime quality-filter q-score \
 --i-demux single-end-demux.qza \
 --o-filtered-sequences demux-filtered.qza \
 --o-filter-stats demux-filter-stats.qza

qiime deblur denoise-16S \
  --i-demultiplexed-seqs demux-filtered.qza \
  --p-trim-length 100 \
  --p-jobs-to-start 36 \
  --o-representative-sequences rep-seqs-deblur.qza \
  --o-table table-deblur.qza \
  --p-sample-stats \
  --o-stats deblur-stats.qza
