#!/bin/bash
#PBS -k o
#PBS -M USEREMAIL
#PBS -m abe
#PHS -N birds_otuc
#PBS -j oe
#PBS -d USERDIRECTORY
#PBS -l walltime=05:10:00,nodes=1:ppn=36,feature=xeon

module load EasyBuild
module load QIIME2
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

qiime vsearch cluster-features-closed-reference \
  --i-table table-deblur.qza \
  --i-sequences rep-seqs-deblur.qza \
  --i-reference-sequences gg_otu_97.qza \
  --p-perc-identity 0.97 \
  --p-threads 0 \
  --o-clustered-table table-cr-97.qza \
  --o-clustered-sequences rep-seqs-cr-97.qza \
  --o-unmatched-sequences unmatched-cr-97.qza
