#!/bin/bash
#PBS -k o
#PBS -M USEREMAIL
#PBS -m abe
#PHS -N bird_import_manual
#PBS -j oe
#PBS -d USERDIRECTORY
#PBS -l walltime=05:00:00,nodes=1:ppn=36,feature=xeon

module load EasyBuild
module load QIIME2
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path manifest.csv \
  --output-path single-end-demux.qza \
  --input-format SingleEndFastqManifestPhred33
